export const projects = [
  {
    name: "Project Nova",
    desc: "A real-time collaborative whiteboard built with WebSockets. Users can brainstorm, draw, and communicate in a shared infinite canvas.",
    tags: ["React", "Node.js", "WebSocket", "Canvas API"],
    link: "#",
    emoji: "🚀",
    color1: "#44aaff",
    color2: "#001166",
    size: 6,
    orbitRadius: 38,
    inclination: 0.4,
    tiltZ: 0.1,
    speed: 0.35,
    phase: 0,
  },
  {
    name: "Terra Dashboard",
    desc: "An analytics dashboard for environmental data. Visualizes CO2 trends, temperature data, and deforestation stats on an interactive globe.",
    tags: ["Vue.js", "D3.js", "Python", "FastAPI"],
    link: "#",
    emoji: "🌍",
    color1: "#44cc66",
    color2: "#003322",
    size: 7,
    orbitRadius: 56,
    inclination: -0.5,
    tiltZ: 0.3,
    speed: 0.22,
    phase: 1.5,
    hasRing: true,
  },
  {
    name: "Pixel Dungeon",
    desc: "A browser-based roguelike with procedurally generated levels, pixel art graphics, and satisfying turn-based combat.",
    tags: ["TypeScript", "Phaser.js", "Webpack"],
    link: "#",
    emoji: "🎮",
    color1: "#ff6644",
    color2: "#440011",
    size: 5.5,
    orbitRadius: 72,
    inclination: 0.7,
    tiltZ: -0.2,
    speed: 0.18,
    phase: 3.2,
  },
  {
    name: "Soundwave",
    desc: "A music visualization app that transforms any audio input into stunning real-time 3D animations using the Web Audio API and WebGL.",
    tags: ["JavaScript", "WebGL", "Web Audio API"],
    link: "#",
    emoji: "🎵",
    color1: "#cc44ff",
    color2: "#220044",
    size: 6.5,
    orbitRadius: 48,
    inclination: 1.1,
    tiltZ: 0.5,
    speed: 0.28,
    phase: 0.8,
    hasRing: true,
  },
  {
    name: "MarketPulse",
    desc: "Real-time stock tracker with AI-powered sentiment analysis, price alerts, and a clean portfolio management interface.",
    tags: ["React", "Python", "ML", "PostgreSQL"],
    link: "#",
    emoji: "📈",
    color1: "#ffcc22",
    color2: "#443300",
    size: 6,
    orbitRadius: 64,
    inclination: -0.3,
    tiltZ: 0.8,
    speed: 0.20,
    phase: 2.1,
  },
  {
    name: "Cipher Chat",
    desc: "End-to-end encrypted messaging with zero-knowledge architecture. Your messages are yours — the server never sees plaintext.",
    tags: ["Rust", "React", "Cryptography", "WebAssembly"],
    link: "#",
    emoji: "🔐",
    color1: "#ff4488",
    color2: "#220011",
    size: 5,
    orbitRadius: 84,
    inclination: 0.9,
    tiltZ: -0.6,
    speed: 0.15,
    phase: 4.5,
  },
];
